// src/lib/gemini.ts
// This file simulates the Gemini AI API call for summary generation.
// In a real application, you would replace this with actual Gemini API integration.

export async function generateSummaryWithGemini(text: string): Promise<string> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500)); 

  if (!text || text.trim().length < 50) {
    throw new Error("Insufficient text to generate a meaningful summary.");
  }

  // Simulate summary generation
  const placeholderSummary = `This is a summary generated by a placeholder Gemini AI model based on the provided text. Key points extracted from the first 100 characters: "${text.substring(0, 100)}..."`;
  
  return placeholderSummary;
}

export async function generateQuizWithGemini(text: string, quizLength: "short" | "medium" | "long"): Promise<any> {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 750)); // Slightly longer delay for quiz generation

  if (!text || text.trim().length < 100) {
    throw new Error("Insufficient text to generate a meaningful quiz.");
  }

  // Simulate quiz generation based on length
  let numberOfQuestions: number;
  switch (quizLength) {
    case "short":
      numberOfQuestions = 3;
      break;
    case "medium":
      numberOfQuestions = 5;
      break;
    case "long":
      numberOfQuestions = 8;
      break;
    default:
      numberOfQuestions = 3; // Default to short
  }

  const placeholderQuiz = {
    title: `Quiz on "${text.substring(0, 50)}..." (${quizLength})`,
    questions: Array.from({ length: numberOfQuestions }).map((_, i) => ({
      id: `q${i + 1}`,
      question: `What is a key concept from the provided text, related to point ${i + 1}?`,
      options: [
        `Option A for question ${i + 1}`,
        `Option B for question ${i + 1}`,
        `Option C for question ${i + 1}`,
        `Option D for question ${i + 1}`,
      ],
      correctAnswer: `Option A for question ${i + 1}`,
      explanation: `This is an explanation for the correct answer to question ${i + 1}, based on the text.`,
    })),
  };

  return placeholderQuiz;
}