import { POST } from '@/app/api/generate/route';
import { createClient } from '@/lib/supabase/server';
import { cookies } from 'next/headers';
import * as geminiLib from '@/lib/gemini';

jest.mock('@/lib/supabase/server');
jest.mock('next/headers');
jest.mock('@/lib/gemini');

const mockSupabase = createClient as jest.Mock;
const mockCookies = cookies as jest.Mock;

const mockGenerateSummaryWithGemini = jest.spyOn(geminiLib, 'generateSummaryWithGemini');
const mockGenerateQuizWithGemini = jest.spyOn(geminiLib, 'generateQuizWithGemini');
const mockHandleGeminiError = jest.spyOn(geminiLib, 'handleGeminiError');


describe('POST /api/generate', () => {
  beforeEach(() => {
    jest.resetAllMocks();
    mockCookies.mockReturnValue({ get: jest.fn() });
    process.env.GEMINI_API_KEY = 'test-api-key'; // Ensure API key is set for tests
    process.env.GEMINI_MODEL_NAME = 'gemini-pro'; // Ensure Gemini model name is set for tests
    // Default successful mocks for Gemini
    mockGenerateSummaryWithGemini.mockResolvedValue('This is a simulated summary generated by Gemini.');
    mockGenerateQuizWithGemini.mockResolvedValue(JSON.stringify({
        questions: [{ question: 'Q1', options: ['A'], answer: 'A', explanation: 'Exp' }]
    }));
    // Note: handleGeminiError now returns a NextResponse object, not just a message.
    mockHandleGeminiError.mockImplementation((error, generationType, requestId) => {
        console.error(`Mock handleGeminiError: ${error.message}`);
        // Simulate NextResponse behavior for testing
        return {
            status: error.status || 500,
            text: async () => `AI ${generationType} generation failed: ${error.message}` // Return a function for .text()
        } as any;
    });
  });

  afterEach(() => {
    delete process.env.GEMINI_API_KEY; // Clean up
    delete process.env.GEMINI_MODEL_NAME; // Clean up
  });

  it('should return 401 if user is not authenticated', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: null } }),
      },
    });

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'summary', documentId: '123' }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(401);
    expect(await response.text()).toBe('Unauthorized');
  });

  it('should return 404 if document is not found', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn().mockReturnValue({
        select: jest.fn().mockReturnValue({
          eq: jest.fn().mockReturnThis(),
          single: jest.fn().mockResolvedValue({ data: null, error: { message: 'Not found' } }),
        }),
      }),
    });

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'summary', documentId: '123' }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(404);
    expect(await response.text()).toBe('Document not found or access denied');
  });

  it('should return 200 and data on success', async () => {
    const mockSummary = { summary: 'This is a summary.' };
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => {
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: 'Some long text that is definitely more than one hundred characters long. This should allow the test to pass without triggering the short text error.' } }),
            }),
          };
        }
        if (table === 'generated_content') {
          return {
            insert: jest.fn().mockReturnValue({
              select: jest.fn().mockResolvedValue({ data: [{ content: mockSummary }], error: null }),
            }),
          };
        };
        return {};
      }),
    });

    mockGenerateSummaryWithGemini.mockResolvedValueOnce('This is a simulated summary generated by Gemini.');

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'summary', documentId: '123' }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual({ content: mockSummary, message: null }); // Expected to be an object with content
    expect(mockGenerateSummaryWithGemini).toHaveBeenCalledWith(
      'Please provide a concise summary of the following text, ensuring the summary is in the same language as the original text: Some long text that is definitely more than one hundred characters long. This should allow the test to pass without triggering the short text error.',
      expect.any(String) // requestId
    );
  });

  it('should return 500 if Gemini API throws an error during summary generation', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn().mockReturnValue({
        select: jest.fn().mockReturnValue({
          eq: jest.fn().mockReturnThis(),
          single: jest.fn().mockResolvedValue({ data: { extracted_text: 'This is a much longer text that should easily exceed the 100 character limit for summarization. This will ensure that the short text error is not triggered and the Gemini API error is properly tested.' } }),
        }),
      }),
    });
    const geminiError = new Error('Gemini summarization failed.') as any;
    geminiError.status = 500;
    mockGenerateSummaryWithGemini.mockRejectedValueOnce(geminiError);

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'summary', documentId: '123' }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(500);
    expect(await response.text()).toBe('AI summary generation failed: Gemini summarization failed.');
  });

  it('should return 500 if Supabase insert for generated content fails', async () => {
    const mockSummary = { summary: 'This is a summary.' };
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => {
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: 'This is a much longer text that should easily exceed the 100 character limit for summarization. This will ensure that the short text error is not triggered and the Supabase insert failure is properly tested.' } }),
            }),
          };
        }
        if (table === 'generated_content') {
          return {
            insert: jest.fn().mockReturnValue({
              select: jest.fn().mockResolvedValue({ data: null, error: { message: 'DB Insert Error' } }),
            }),
          };
        }
        return {};
      }),
    });
    mockGenerateSummaryWithGemini.mockResolvedValueOnce('This is a simulated summary generated by Gemini.');

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'summary', documentId: '123' }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(500);
    expect(await response.text()).toBe('Internal Server Error');
  });

  it('should return 500 for a generic unexpected error', async () => {
    // Simulate an error in the initial document retrieval
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn().mockImplementation(() => { // Mock 'from' to throw an error
        throw new Error('Unexpected DB connection error');
      }),
    });

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'summary', documentId: '123' }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(500);
    expect(await response.text()).toBe('An unexpected internal server error occurred.'); // Updated error message
  });

  it('should return 400 if document.extracted_text is null for summary type', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn().mockReturnValue({
        select: jest.fn().mockReturnValue({
          eq: jest.fn().mockReturnThis(),
          single: jest.fn().mockResolvedValue({ data: { extracted_text: null }, error: null }),
        }),
      }),
    });

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'summary', documentId: '123' }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(400);
    expect(await response.text()).toBe('Document has no text content to summarize');
  });

  it('should return 400 if document.extracted_text is an empty string for quiz type', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn().mockReturnValue({
        select: jest.fn().mockReturnValue({
          eq: jest.fn().mockReturnThis(),
          single: jest.fn().mockResolvedValue({ data: { extracted_text: '' }, error: null }),
        }),
      }),
    });

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'quiz', documentId: '123', options: { quizLength: 'short' } }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(400);
    expect(await response.text()).toBe('Document has no text content to summarize');
  });

  it('should return 400 if document.extracted_text is a very short string for quiz type', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn().mockReturnValue({
        select: jest.fn().mockReturnValue({
          eq: jest.fn().mockReturnThis(),
          single: jest.fn().mockResolvedValue({ data: { extracted_text: 'too short' }, error: null }),
        }),
      }),
    });

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'quiz', documentId: '123', options: { quizLength: 'short' } }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(400);
    expect(await response.text()).toBe('Document content is too short for meaningful quiz generation.');
  });

  it('should adjust to "short" quiz when requesting "long" with content (100-499 chars)', async () => {
    const textBetween100And499 = 'This text has more than 100 characters but less than 500. It is suitable for a short quiz. '.repeat(4); // ~360 chars
    const mockQuiz = [{ question: 'Q1', options: ['A'], answer: 'A', explanation: 'Exp' }];
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => {
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: textBetween100And499 } }),
            }),
          };
        }
        if (table === 'generated_content') {
          return {
            insert: jest.fn().mockReturnValue({
              select: jest.fn().mockResolvedValue({ data: [{ content: { quiz: mockQuiz, message: "The document content is too short to generate a long quiz. Generating a short quiz instead." } }], error: null }),
            }),
          };
        }
        return {};
      }),
    });
    mockGenerateQuizWithGemini.mockResolvedValueOnce(JSON.stringify(mockQuiz));

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'long' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual({ content: { quiz: mockQuiz, message: "The document content is too short to generate a long quiz. Generating a short quiz instead." }, message: "The document content is too short to generate a long quiz. Generating a short quiz instead." });
    expect(mockGenerateQuizWithGemini).toHaveBeenCalledWith(
      'Generate a short multiple-choice quiz (3-5 questions) from the following text. Provide the output as a JSON array of objects, where each object has \'question\', \'options\' (an array of strings), \'answer\' (the correct option string), and \'explanation\' (a string explaining the correct answer). Text: ' + textBetween100And499,
      expect.any(String) // requestId
    );
  });

  it('should adjust to "medium" quiz when requesting "long" with medium content (500-1500 chars)', async () => {
    const mediumText = 'This is a medium length text. It is long enough to be between 500 and 1500 characters. '.repeat(10); // ~700 chars
    const mockQuiz = [{ question: 'Q1', options: ['A'], answer: 'A', explanation: 'Exp' }];
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => {
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: mediumText } }),
            }),
          };
        }
        if (table === 'generated_content') {
          return {
            insert: jest.fn().mockReturnValue({
              select: jest.fn().mockResolvedValue({ data: [{ content: { quiz: mockQuiz, message: "The document content is not sufficient for a long quiz. Generating a medium quiz instead." } }], error: null }),
            }),
          };
        }
        return {};
      }),
    });
    mockGenerateQuizWithGemini.mockResolvedValueOnce(JSON.stringify(mockQuiz));

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'long' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual({ content: { quiz: mockQuiz, message: "The document content is not sufficient for a long quiz. Generating a medium quiz instead." }, message: "The document content is not sufficient for a long quiz. Generating a medium quiz instead." });
    expect(mockGenerateQuizWithGemini).toHaveBeenCalledWith(
      'Generate a medium multiple-choice quiz (6-8 questions) from the following text. Provide the output as a JSON array of objects, where each object has \'question\', \'options\' (an array of strings), \'answer\' (the correct option string), and \'explanation\' (a string explaining the correct answer). Text: ' + mediumText,
      expect.any(String) // requestId
    );
  });

  it('should adjust to "short" quiz when requesting "medium" with content (100-499 chars)', async () => {
    const textBetween100And499 = 'This text has more than 100 characters but less than 500. It is suitable for a short quiz. '.repeat(4); // ~360 chars
    const mockQuiz = [{ question: 'Q1', options: ['A'], answer: 'A', explanation: 'Exp' }];
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => {
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: textBetween100And499 } }),
            }),
          };
        }
        if (table === 'generated_content') {
          return {
            insert: jest.fn().mockReturnValue({
              select: jest.fn().mockResolvedValue({ data: [{ content: { quiz: mockQuiz, message: "The document content is too short to generate a medium quiz. Generating a short quiz instead." } }], error: null }),
            }),
          };
        }
        return {};
      }),
    });
    mockGenerateQuizWithGemini.mockResolvedValueOnce(JSON.stringify(mockQuiz));

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'medium' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual({ content: { quiz: mockQuiz, message: "The document content is too short to generate a medium quiz. Generating a short quiz instead." }, message: "The document content is too short to generate a medium quiz. Generating a short quiz instead." });
    expect(mockGenerateQuizWithGemini).toHaveBeenCalledWith(
      'Generate a short multiple-choice quiz (3-5 questions) from the following text. Provide the output as a JSON array of objects, where each object has \'question\', \'options\' (an array of strings), \'answer\' (the correct option string), and \'explanation\' (a string explaining the correct answer). Text: ' + textBetween100And499,
      expect.any(String) // requestId
    );
  });

  it('should adjust to "medium" quiz when requesting "long" with content (500-1499 chars)', async () => {
    const textBetween500And1499 = 'This text has more than 500 characters but less than 1500. It is suitable for a medium quiz. '.repeat(10); // ~900 chars
    const mockQuiz = [{ question: 'Q1', options: ['A'], answer: 'A', explanation: 'Exp' }];
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => {
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: textBetween500And1499 } }),
            }),
          };
        }
        if (table === 'generated_content') {
          return {
            insert: jest.fn().mockReturnValue({
              select: jest.fn().mockResolvedValue({ data: [{ content: { quiz: mockQuiz, message: "The document content is not sufficient for a long quiz. Generating a medium quiz instead." } }], error: null }),
            }),
          };
        }
        return {};
      }),
    });
    mockGenerateQuizWithGemini.mockResolvedValueOnce(JSON.stringify(mockQuiz));

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'long' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual({ content: { quiz: mockQuiz, message: "The document content is not sufficient for a long quiz. Generating a medium quiz instead." }, message: "The document content is not sufficient for a long quiz. Generating a medium quiz instead." });
    expect(mockGenerateQuizWithGemini).toHaveBeenCalledWith(
      'Generate a medium multiple-choice quiz (6-8 questions) from the following text. Provide the output as a JSON array of objects, where each object has \'question\', \'options\' (an array of strings), \'answer\' (the correct option string), and \'explanation\' (a string explaining the correct answer). Text: ' + textBetween500And1499,
      expect.any(String) // requestId
    );
  });
  
  it('should generate "short" quiz as requested with sufficient content', async () => {
    const longText = 'This is a very long text that can support any quiz length. '.repeat(100); // > 1500 chars
    const mockQuiz = [{ question: 'Q1', options: ['A'], answer: 'A', explanation: 'Exp' }];
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => {
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: longText } }),
            }),
          };
        }
        if (table === 'generated_content') {
          return {
            insert: jest.fn().mockReturnValue({
              select: jest.fn().mockResolvedValue({ data: [{ content: { quiz: mockQuiz, message: null } }], error: null }),
            }),
          };
        }
        return {};
      }),
    });
    mockGenerateQuizWithGemini.mockResolvedValueOnce(JSON.stringify(mockQuiz));

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'short' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual({ content: { quiz: mockQuiz, message: null }, message: null });
    expect(mockGenerateQuizWithGemini).toHaveBeenCalledWith(
      'Generate a short multiple-choice quiz (3-5 questions) from the following text. Provide the output as a JSON array of objects, where each object has \'question\', \'options\' (an array of strings), \'answer\' (the correct option string), and \'explanation\' (a string explaining the correct answer). Text: ' + longText,
      expect.any(String) // requestId
    );
  });

  it('should generate "medium" quiz as requested with sufficient content', async () => {
    const longText = 'This is a very long text that can support any quiz length. It needs to be at least 1500 characters for a long quiz and 500 for a medium quiz. '.repeat(100); // Ensures > 1500 chars
    const mockQuiz = [{ question: 'Q1', options: ['A'], answer: 'A', explanation: 'Exp' }];
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => {
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: longText, class_section_id: 'class-1' } }),
            }),
          };
        }
        if (table === 'generated_content') {
          return {
            insert: jest.fn().mockReturnValue({
              select: jest.fn().mockResolvedValue({ data: [{ content: { quiz: mockQuiz, message: null } }], error: null }),
            }),
          };
        }
        return {};
      }),
    });
    mockGenerateQuizWithGemini.mockResolvedValueOnce(JSON.stringify(mockQuiz));

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'medium' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual({ content: { quiz: mockQuiz, message: null }, message: null });
    expect(mockGenerateQuizWithGemini).toHaveBeenCalledWith(
      'Generate a medium multiple-choice quiz (6-8 questions) from the following text. Provide the output as a JSON array of objects, where each object has \'question\', \'options\' (an array of strings), \'answer\' (the correct option string), and \'explanation\' (a string explaining the correct answer). Text: ' + longText,
      expect.any(String) // requestId
    );
  });


  it('should generate "long" quiz as requested with sufficient content', async () => {
    const longText = 'This is a very long text that can support any quiz length. It needs to be at least 1500 characters for a long quiz and 500 for a medium quiz. '.repeat(100); // Ensures > 1500 chars
    const mockQuiz = [{ question: 'Q1', options: ['A'], answer: 'A', explanation: 'Exp' }];
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => {
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: longText, class_section_id: 'class-1' } }),
            }),
          };
        }
        if (table === 'generated_content') {
          return {
            insert: jest.fn().mockReturnValue({
              select: jest.fn().mockResolvedValue({ data: [{ content: { quiz: mockQuiz, message: null } }], error: null }),
            }),
          };
        }
        return {};
      }),
    });
    mockGenerateQuizWithGemini.mockResolvedValueOnce(JSON.stringify(mockQuiz));

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'long' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual({ content: { quiz: mockQuiz, message: null }, message: null });
    expect(mockGenerateQuizWithGemini).toHaveBeenCalledWith(
      'Generate a long multiple-choice quiz (9-12 questions) from the following text. Provide the output as a JSON array of objects, where each object has \'question\', \'options\' (an array of strings), \'answer\' (the correct option string), and \'explanation\' (a string explaining the correct answer). Text: ' + longText,
      expect.any(String) // requestId
    );
  });

  it('should return 400 if type is neither summary nor quiz', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn(() => ({})), // Mock 'from' to return an empty object, preventing TypeError
    });

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'invalid', documentId: '123' }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(400);
    expect(await response.text()).toBe('Invalid type');
  });

  it('should return 200 and quiz data on successful quiz generation', async () => {
    const mockQuiz = {
      title: 'Test Quiz',
      questions: [
        { id: '1', question: 'Test Q', options: ['A', 'B'], correctAnswer: 'A' },
      ],
    };
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => {
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: 'This is a very long text that can support any quiz length. It is definitely more than one hundred characters long.', class_section_id: 'class-1' } }),
            }),
          };
        }
        if (table === 'generated_content') {
          return {
            insert: jest.fn().mockReturnValue({
              select: jest.fn().mockResolvedValue({ data: [{ content: { quiz: mockQuiz, message: null } }], error: null }),
            }),
          };
        }
        return {};
      }),
    });
    mockGenerateQuizWithGemini.mockResolvedValueOnce(JSON.stringify(mockQuiz));

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'short' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual({ content: { quiz: mockQuiz, message: null }, message: null });
    expect(mockGenerateQuizWithGemini).toHaveBeenCalledWith(
      'Generate a short multiple-choice quiz (3-5 questions) from the following text. Provide the output as a JSON array of objects, where each object has \'question\', \'options\' (an array of strings), \'answer\' (the correct option string), and \'explanation\' (a string explaining the correct answer). Text: ' + 'This is a very long text that can support any quiz length. It is definitely more than one hundred characters long.',
      expect.any(String) // requestId
    );
  });

  it('should return 400 if quizLength is missing for quiz type', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn((table: string) => { // Added mock for 'from'
        if (table === 'study_materials') {
          return {
            select: jest.fn().mockReturnValue({
              eq: jest.fn().mockReturnThis(),
              single: jest.fn().mockResolvedValue({ data: { extracted_text: 'Some text' }, error: null }),
            }),
          };
        }
        return {}; // Default return for other tables
      }),
    });

    const req = {
      json: jest.fn().mockResolvedValue({ type: 'quiz', documentId: '123' }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(400);
    expect(await response.text()).toBe('Invalid or missing quizLength option');
  });

  it('should return 500 if Gemini API throws an error during quiz generation', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn().mockReturnValue({
        select: jest.fn().mockReturnValue({
          eq: jest.fn().mockReturnThis(),
          single: jest.fn().mockResolvedValue({ data: { extracted_text: 'Short text for quiz' } }),
        }),
      }),
    });
    const geminiError = new Error('Gemini quiz generation failed.') as any;
    geminiError.status = 500;
    mockGenerateQuizWithGemini.mockRejectedValueOnce(geminiError);

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'short' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(500);
    expect(await response.text()).toBe('AI quiz generation failed: Gemini quiz generation failed.');
  });

  it('should handle Gemini API 401 Unauthorized error correctly', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn().mockReturnValue({
        select: jest.fn().mockReturnValue({
          eq: jest.fn().mockReturnThis(),
          single: jest.fn().mockResolvedValue({ data: { extracted_text: 'Some text for quiz', class_section_id: 'class-1' } }),
        }),
      }),
    });

    const geminiError = new Error('Invalid API Key') as any;
    geminiError.status = 401;
    mockGenerateQuizWithGemini.mockRejectedValueOnce(geminiError);

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'short' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(401);
    expect(await response.text()).toBe('Authentication/Authorization error with Gemini API. Please check your API key.');
  });

  it('should handle Gemini API 429 Rate Limit Exceeded error correctly', async () => {
    mockSupabase.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: 'user-1' } } } }),
      },
      from: jest.fn().mockReturnValue({
        select: jest.fn().mockReturnValue({
          eq: jest.fn().mockReturnThis(),
          single: jest.fn().mockResolvedValue({ data: { extracted_text: 'Some text for quiz', class_section_id: 'class-1' } }),
        }),
      }),
    });

    const geminiError = new Error('Rate limit exceeded') as any;
    geminiError.status = 429;
    mockGenerateQuizWithGemini.mockRejectedValueOnce(geminiError);

    const req = {
      json: jest.fn().mockResolvedValue({
        type: 'quiz',
        documentId: '123',
        options: { quizLength: 'short' },
      }),
    } as any;

    const response = await POST(req);
    expect(response.status).toBe(429);
    expect(await response.text()).toBe('Gemini API rate limit exceeded. Please try again shortly.');
  });
});