import { POST } from '@/app/api/generate/route';
import { createClient } from '@/lib/supabase/server';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { cookies } from 'next/headers';

jest.mock('@/lib/supabase/server');
jest.mock('@google/generative-ai');
jest.mock('next/headers');

const mockCreateClient = createClient as jest.Mock;
const mockGoogleGenerativeAI = GoogleGenerativeAI as jest.Mock;
const mockCookies = cookies as jest.Mock;

describe('Integration: POST /api/generate', () => {
  const MOCK_USER_ID = 'user-uuid-123';
  const MOCK_DOCUMENT_ID = 'doc-uuid-456';
  const MOCK_EXTRACTED_TEXT = 'This is a sufficiently long text to be summarized by the AI. It contains various details relevant to the document content.';
  const MOCK_SUMMARY_CONTENT = 'This is a mock summary generated by Gemini.';

  let mockFrom: jest.Mock;
  let mockSelect: jest.Mock;
  let mockEq: jest.Mock;
  let mockSingle: jest.Mock;
  let mockInsert: jest.Mock;
  let mockGenerateContent: jest.Mock;

  beforeEach(() => {
    jest.resetAllMocks();

    mockSelect = jest.fn();
    mockEq = jest.fn();
    mockSingle = jest.fn();
    mockInsert = jest.fn();

    mockFrom = jest.fn((tableName: string) => {
      if (tableName === 'study_materials') {
        return {
          select: mockSelect.mockReturnThis(),
          eq: mockEq.mockReturnThis(),
          single: mockSingle,
        };
      }
      if (tableName === 'generated_content') {
        return {
          insert: mockInsert.mockImplementation((data: any) => {
            return {
              select: jest.fn().mockResolvedValueOnce({ data, error: null }),
            };
          }),
        };
      }
      return jest.fn();
    });

    mockCreateClient.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: { user: { id: MOCK_USER_ID } } } }),
      },
      from: mockFrom,
    });

    mockCookies.mockReturnValue({
      get: jest.fn(),
    });
    
    mockGenerateContent = jest.fn().mockResolvedValue({
        response: {
            text: () => MOCK_SUMMARY_CONTENT,
        },
    });

    mockGoogleGenerativeAI.mockImplementation(() => ({
        getGenerativeModel: () => ({
            generateContent: mockGenerateContent,
        }),
    }));
  });

  it('should return 401 if user is not authenticated', async () => {
    mockCreateClient.mockReturnValue({
      auth: {
        getSession: jest.fn().mockResolvedValue({ data: { session: null } }),
      },
      from: mockFrom,
    });

    const req = {
      json: () => Promise.resolve({ type: 'summary', documentId: MOCK_DOCUMENT_ID }),
    } as unknown as Request;

    const response = await POST(req);
    expect(response.status).toBe(401);
    const body = await response.text();
    expect(body).toBe('Unauthorized');
  });

  it('should return 400 if type is not "summary"', async () => {
    const req = {
      json: () => Promise.resolve({ type: 'quiz', documentId: MOCK_DOCUMENT_ID }),
    } as unknown as Request;

    const response = await POST(req);
    expect(response.status).toBe(400);
    const body = await response.text();
    expect(body).toBe('Invalid type');
  });

  it('should return 400 if documentId is missing', async () => {
    const req = {
      json: () => Promise.resolve({ type: 'summary' }),
    } as unknown as Request;

    const response = await POST(req);
    expect(response.status).toBe(400);
    const body = await response.text();
    expect(body).toBe('Missing documentId');
  });

  it('should return 404 if document not found or access denied', async () => {
    mockSingle.mockResolvedValue({ data: null, error: { message: 'Document not found' } });

    const req = {
      json: () => Promise.resolve({ type: 'summary', documentId: MOCK_DOCUMENT_ID }),
    } as unknown as Request;

    const response = await POST(req);
    expect(response.status).toBe(404);
    const body = await response.text();
    expect(body).toBe('Document not found or access denied');
  });

  it('should return 400 if document has no extracted text', async () => {
    mockSingle.mockResolvedValue({ data: { extracted_text: null }, error: null });

    const req = {
      json: () => Promise.resolve({ type: 'summary', documentId: MOCK_DOCUMENT_ID }),
    } as unknown as Request;

    const response = await POST(req);
    expect(response.status).toBe(400);
    const body = await response.text();
    expect(body).toBe('Document has no text content to summarize');
  });

  it('should return 500 if Gemini API call fails', async () => {
    mockSingle.mockResolvedValue({ data: { extracted_text: MOCK_EXTRACTED_TEXT }, error: null });
    mockGenerateContent.mockRejectedValue(new Error('AI service unavailable'));

    const req = {
      json: () => Promise.resolve({ type: 'summary', documentId: MOCK_DOCUMENT_ID }),
    } as unknown as Request;

    const response = await POST(req);
    expect(response.status).toBe(500);
    const body = await response.text();
    expect(body).toBe('Failed to generate summary with Gemini AI.');
  });

  it('should return 500 if storing generated content fails', async () => {
    mockSingle.mockResolvedValue({ data: { extracted_text: MOCK_EXTRACTED_TEXT }, error: null });
    mockInsert.mockImplementationOnce(() => {
      return {
        select: jest.fn().mockResolvedValueOnce({ data: null, error: { message: 'DB write error' } }),
      };
    });

    const req = {
      json: () => Promise.resolve({ type: 'summary', documentId: MOCK_DOCUMENT_ID }),
    } as unknown as Request;

    const response = await POST(req);
    expect(response.status).toBe(500);
    const body = await response.text();
    expect(body).toBe('Internal Server Error');
  });

  it('should successfully generate and store a summary', async () => {
    mockSingle.mockResolvedValue({ data: { extracted_text: MOCK_EXTRACTED_TEXT }, error: null });
    const mockReturnedData = [{ id: 'gen-uuid-789', content: { summary: MOCK_SUMMARY_CONTENT } }];
    mockInsert.mockImplementationOnce(() => {
      return {
        select: jest.fn().mockResolvedValueOnce({ data: mockReturnedData, error: null }),
      };
    });

    const req = {
      json: () => Promise.resolve({ type: 'summary', documentId: MOCK_DOCUMENT_ID }),
    } as unknown as Request;

    const response = await POST(req);
    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual(mockReturnedData);

    expect(mockCreateClient).toHaveBeenCalled();
    expect(mockFrom).toHaveBeenCalledWith('study_materials');
    expect(mockEq).toHaveBeenCalledWith('id', MOCK_DOCUMENT_ID);
    expect(mockEq).toHaveBeenCalledWith('user_id', MOCK_USER_ID);
    expect(mockFrom).toHaveBeenCalledWith('generated_content');
    expect(mockInsert).toHaveBeenCalledWith([
      {
        user_id: MOCK_USER_ID,
        study_material_id: MOCK_DOCUMENT_ID,
        content_type: 'summary',
        content: { summary: MOCK_SUMMARY_CONTENT },
      },
    ]);
  });

  it('should call Gemini with the correct summary prompt', async () => {
    mockSingle.mockResolvedValue({ data: { extracted_text: MOCK_EXTRACTED_TEXT }, error: null });

    const req = {
      json: () => Promise.resolve({ type: 'summary', documentId: MOCK_DOCUMENT_ID }),
    } as unknown as Request;

    await POST(req);

    expect(mockGenerateContent).toHaveBeenCalledTimes(1);
    expect(mockGenerateContent).toHaveBeenCalledWith(
      `Summarize the following text in a concise way, highlighting the key points:\n\n${MOCK_EXTRACTED_TEXT}`
    );
  });
});